// Reads Foundry artifacts and writes `as const` ABI modules. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "..", "contracts", "out");

const targets = [
  ["Vault.sol/Vault.json", "vaultAbi", "vault.ts"],
  ["VerifierRegistry.sol/VerifierRegistry.json", "verifierRegistryAbi", "verifierRegistry.ts"],
];

for (const [artifact, name, file] of targets) {
  const json = JSON.parse(readFileSync(join(out, artifact), "utf8"));
  const body = `// Generated by scripts/extract.mjs from contracts/out/${artifact}. Do not edit.\nexport const ${name} = ${JSON.stringify(json.abi, null, 2)} as const;\n`;
  writeFileSync(join(here, "..", "src", file), body);
  console.log(`wrote src/${file} (${json.abi.length} entries)`);
}
